### PR TITLE
Configure deployment to Maven Central

### PR DESCRIPTION
**Pull request by leonardehrenfried**
I configured sbt to deploy snapshots and releases to Sonatypo and via that to Maven Central.

You need to set up PGP keys and make an account at Sonatype. I've written a fairly detailed guide on my blog: https://leonard.io/blog/2017/01/an-in-depth-guide-to-deploying-to-maven-central/

(If you notice that something doesn't work let me know.)

You probably want to remove the bintray plugin.

### CODE REVIEW

**Comment by jilen** [comment]
`play-circe` maybe illegal organization. We had to name it `com.github.jilen` ...

**Comment by leonardehrenfried** [comment]
Yes, it will be better to rename the group.

**Comment by leonardehrenfried** [comment]
Hey, how is this coming along? Do you need help with this?

**Comment by jilen** [comment]
@leonardehrenfried  I was just on my  vacation. Will do this in few days

**Pull request merged**
